apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-system:openshift:scc:{{ .Release.Name}}-uid1000
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - {{ .Release.Name}}-uid1000
  resources:
  - securitycontextconstraints
  verbs:
  - use
