apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name}}-system:openshift:scc:{{ .Release.Name}}-uid1000
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-system:openshift:scc:{{ .Release.Name}}-uid1000 
subjects:
- kind: ServiceAccount
  name: {{ include "step-certificates.fullname" . }}-config 
  namespace: {{ .Release.Namespace }}
