apiVersion: v1
kind: Service
metadata:
  name: {{ include "step-certificates.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "step-certificates.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "step-certificates.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
