apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "smallstep"
  namespace: "argocd"
spec:
  destination:
    namespace: smallstep
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/advatys/smallstep-helm-charts.git
    targetRevision: openshift
    path: step-certificates
    helm:
      values: |
        ca:
          bootstrap:
            # Add script snippets here to be executed after the step ca init has been run
            postInitHook: |-
              step ca provisioner add Google --type oidc --ca-config $(step path)/config/ca.json \
              --client-id 650445034027-jsjdrkiskeq9ke99ud2rqkst82ft8uch.apps.googleusercontent.com \
              --client-secret 6Q7lGMua_Oox4nA92QBXYypT \
              --configuration-endpoint https://accounts.google.com/.well-known/openid-configuration \
              --domain smallstep.com --domain gmail.com
         

